### ISSUE TITLE
FR: Allow for polling intervals to refresh the screen automatically instead of doing so manually

### ISSUE THREAD

**Issue by improvethings** [vishalxl/nostr_console#22]
let's say I choose to poll every 30 seconds, it'll refresh my screen every 30 seconds instead of hitting "1" over and over. Instead of timed intervals, I might also choose for any event, or just for new events from people I follow.

**Comment by vishalxl** [comment]
Hi, right now when the application is waiting for input, nothing in backgroud can run, that's how I'm using the Dart language works stdin input. Since right now stdin is read one line at a time. Till a user presses 'enter', the thread blocks. 

This can be changed so that input is taken one char at a time, then background updates can happen and can be shown when desired. The work to do this is pretty high, so its not on priority right now.
